# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bcda89713a497e30fed8a8d14a6bea0de537b679237fa614d55bf1aa42d3eab446e24cf5948bf0f3094b6619d0f309b2a98f7f4573289e8d9f83c0f3e0f5a59

test:
  secret_key_base: 25ba878a44fffbe0cec4752402c7080d7403092181e50a799d55dd297541fad17b0c0ab0976a468c858e1953332dc1f43ec4f8b1fadd1ca40d9e902fd436b743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
